# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "skywalking.fullname" . }}-oap
  labels:
    app: {{ .Values.oap.name }}
spec:
  replicas: {{ .Values.oap.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.oap.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.oap.name }}
    spec:
      serviceAccountName: {{ .Values.oap.name }}
      containers:
      - name: {{ .Values.oap.name }}
        image: {{ .Values.oap.image.repository }}:{{ .Values.oap.image.tag }}
        ports:
        - containerPort: {{ .Values.oap.ports.grpc }}
          name: grpc
        - containerPort: {{ .Values.oap.ports.rest }}
          name: rest
        resources:
          requests:
            memory: {{ .Values.oap.resources.requests.memory }}
          limits:
            memory: {{ .Values.oap.resources.limits.memory }}
        env:
        - name: JAVA_OPTS
          value: {{ .Values.oap.env.javaOpts }}
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: config
          mountPath: /skywalking/config
      volumes:
      - name: config
        configMap:
          name: {{ template "skywalking.fullname" . }}-oap-config